import { useSession } from "next-auth/react";
import Head from "next/head";
import StockSidebar from "~/components/left_panel/stockSidebar";
import Headbar from "~/components/headbar";
import NewsSidebar from "~/components/right_panel/newsSidebar";
import Graph from "~/components/main_panel/graph";
import ControlPanel from "~/components/main_panel/controlPanel";
import { useState } from "react";
import Portfolio from "~/components/main_panel/portfolio";
import { StockProvider, UserDataProvider } from "~/dataContext";
import AuthPage from "~/components/authPage";
import Image from "next/image";
import logo from "../../public/logo.png";

export default function Home() {
  const [displayPortfolio, setDisplayPortfolio] = useState(false);
  const [graphData, setGraphData] = useState({
    name: "",
    startPrice: 0,
  });

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen min-h-full w-screen min-w-full flex-col">
        {sessionData ? (
          <StockProvider>
            <UserDataProvider>
              <Headbar
                displayPortfolio={displayPortfolio}
                setDisplayPortfolio={setDisplayPortfolio}
              />
              <div className="flex h-full flex-row">
                <StockSidebar setGraphData={setGraphData} />
                <div className="relative flex w-full flex-col overflow-hidden">
                  {displayPortfolio ? (
                    <Portfolio setDisplayPortfolio={setDisplayPortfolio} />
                  ) : (
                    <>
                      {graphData.name === "" ? (
                        <div className="relative z-10 flex h-full w-full min-w-full items-center justify-center self-stretch">
                          <Image
                            src={logo}
                            alt="logo"
                            height={500}
                            className="opacity-10"
                          />
                        </div>
                      ) : (
                        <>
                          <Graph
                            company={graphData.name}
                            startPrice={graphData.startPrice}
                          />
                          <ControlPanel company={graphData.name} />
                        </>
                      )}
                    </>
                  )}
                </div>
                <NewsSidebar />
              </div>
            </UserDataProvider>
          </StockProvider>
        ) : (
          <AuthPage />
        )}
      </main>
    </>
  );
}
